version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --run-syncdb && gunicorn -w 1 --bind 0.0.0.0:8000 api.wsgi"
    container_name: product_service
    volumes:
      - .:/product_service
    ports:
      - "8000:8000"

  